
running 1 test
test tests::test_ivc_nondet_with_compression ... FAILED

failures:

---- tests::test_ivc_nondet_with_compression stdout ----
LONG WIT 13827, SPLITS [
    1,
    2,
    13824,
]
LONG WIT 14341, SPLITS [
    1,
    2,
    14338,
]
LONG WIT 13827, SPLITS [
    1,
    2,
    13824,
]
LONG WIT 14341, SPLITS [
    1,
    2,
    14338,
]
LONG WIT 13827, SPLITS [
    1,
    2,
    13824,
]
LONG WIT 14341, SPLITS [
    1,
    2,
    14338,
]
thread 'tests::test_ivc_nondet_with_compression' panicked at src/lib.rs:1578:5:
assertion failed: res.is_ok()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    tests::test_ivc_nondet_with_compression

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 48 filtered out; finished in 11.94s

